services:
    vaultwarden:
      image: vaultwarden/server:latest
      container_name: vaultwarden
      restart: always
      environment:
        ADMIN_TOKEN: 'supersecretpassword'
      volumes:
        - /vw-data/:/data/
      ports:
        - "8080:80"