services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    environment:
      TZ: "Europe/Berlin"
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
      - '1514:1514'
      - '1515:1515'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
